# Generated by Django 6.0.6 on 2026-07-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
    ]
