# Generated by Django 6.0.6 on 2026-07-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 7, 2)),
            preserve_default=False,
        ),
    ]
