# Generated by Django 5.2.10 on 2026-07-03 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customer_id_alter_jobtype_id_alter_status_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customer", options={"ordering": ["name"]},),
        migrations.AddField(
            model_name="ticket",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobtype",
            name="duration",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="jobtype",
            name="type",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="color",
            field=models.CharField(default="#c79c3d", max_length=20),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="TicketPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tickets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.ticket",
                    ),
                ),
            ],
        ),
    ]
