# Generated by Django 6.0.6 on 2026-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ring_finger',
            field=models.CharField(blank=True, choices=[('left_thumb', 'Left Thumb'), ('left_index', 'Left Index'), ('left_middle', 'Left Middle'), ('left_ring', 'Left Ring'), ('left_little', 'Left Little'), ('right_thumb', 'Right Thumb'), ('right_index', 'Right Index'), ('right_middle', 'Right Middle'), ('right_ring', 'Right Ring'), ('right_little', 'Right Little')], max_length=20, null=True),
        ),
    ]
