# Generated by Django 5.2.17 on 2026-09-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_auditlog_id_alter_customer_id_alter_jobtype_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_starred",
            field=models.BooleanField(default=False),
        ),
    ]
