# Generated by Django 6.1.1 on 2026-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_auditlog_id_alter_customer_id_alter_jobtype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
