# Generated by Django 6.1.1 on 2026-10-06 16:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customer_wedding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[core.models.validate_mold_word])),
            ],
        ),
        migrations.CreateModel(
            name='MoldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[core.models.validate_mold_word])),
            ],
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mold_code', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='molds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='molds', to='core.moldtag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='molds', to='core.moldtype')),
            ],
        ),
    ]
