# Generated by Django 6.1.1 on 2026-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_moldtag_moldtype_mold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mold',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
